---
# https://www.opendata.dk/city-of-aarhus/realtids-trafikdata
# https://www.openstreetmap.org/#map=19/56.21509/10.13978
sensor:
  platform: rest
  name: "[Live Traffic] Søftenvej, Lisbjerg Parkvej (avgSpeed)"
  resource: https://admin.opendata.dk/api/3/action/datastore_search?q=158415&resource_id=b3eeb0ff-c8a8-4824-99d6-e0a3747c8b0d
  method: GET
  json_attributes_path: "result.records[0]"
  json_attributes:
    - _id
    - REPORT_ID
    - TIMESTAMP
    - status
    - avgMeasuredTime
    - medianMeasuredTime
    - vehicleCount
    - avgSpeed
  value_template: '{{ value_json.result.records[0].avgSpeed }}'
  scan_interval: 60
  force_update: false
